import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
      <span>
        Home Page
      </span>
=======
      <div>
        
      </div>
>>>>>>> fb469fdae1964ad3cd8e7e192c2c53b85f85ad2d
    </>
  );
}
